site_name: SennLab
site_description: SennLab Blogs
site_url: https://blog.sennlab.com

theme:
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  custom_dir: overrides/
  features:
    - navigation.tabs
    - navigation.sections  # Useful for an overview
    - navigation.indexes  # Needed for an overview

nav:
  - Any name: blog
  - Tags: tags.md
  - missions: missions/index.md

plugins:
  - search
  - pub-blog:
      teaser_marker: "<!-- more -->"
      searchable_non_posts: false
      posts_per_page: 5
      slug: blog
      blog_dir: 03_blog
  - pub-meta:
      dir_meta_file: README.md
  - pub-social:
      site_name_in_title:
        location: after
        delimiter: " - "
      og:
        enabled: true
        locale: en_us
  - section-index

markdown_extensions:
  - footnotes
  - tables