site_name: SennLab
site_description: SennLab Blogs
site_url: https://sennlabs.github.io
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
plugins:
  - search
  - blog
  - tags:
      tags_file: blog/tags.md
nav:
  # - Home: index.md
  # - Install: install.md
  # - Usage: usage.md
  - Blog:
    - blog/index.md
  - Tags: blog/tags.md